fix: use uid in the retry request and namespace in body
...hopefully fixing error "TypeError: ArchivedWorkflowServiceApi.retry_archived_workflow() missing 1 required positional argument: uid"
while also addressing the empty namespace issue